### ISSUE TITLE
Innacurate reading values using getVescValues

### ISSUE THREAD

**Issue by joseguerr** [Peemouse/VescUart#1]
Sorry for the delay @Peemouse I just had left work. I am opening here the issue as you previsouly asked me. Regarding the getVescValues Arduino sketch, i am getting these weird values as seen below.

![58190627-dae66300-7cb4-11e9-9531-dcc899ced34d](https://user-images.githubusercontent.com/37153384/58201032-0759a980-7ccc-11e9-9281-396b0df5ba46.png)

For context, these values were read for both your previous and updated versions. I used both baudrates at 115200 and added the line UART.setDebugPort(&Serial); after UART.setSerialPort(&Serial1); . Did not touch in the c++ files. Tomorrow, once I am back at work i will proceed with any suggestion that you may find relevant. Again, thank you so much for your help.

**Comment by Peemouse** [comment]
The issue is mostly VESC side as the command sent by the Arduino is correct but the VESC answer is empty.
I mean, the protocol is fine, the command byte and mask are ok but no values !
FW 3.56, right ?

**Comment by joseguerr** [comment]
Yes, FW 3.56. The thing was that I had no motor connected to the VESC. I don't know if that was the problem but after assembling the motor and connecting it to the VESC the values were ok. Now, time to learn c++. Again, thank you for your help! Much appreciated  👍

**Comment by Peemouse** [comment]
Good to hear. But still a bit strange about the motor connection.
Anyway, thanks for reporting.
Enjoy !

**Comment by joseguerr** [comment]
Sorry to bother you again @Peemouse ..
The issue about wrong rpm readings is still persisting. What I have done so far is trying out two different VESCs and two different motors but did not have success. I am also not getting values regarding battery voltage. Values for battery current are 0 in one of the VESCs and on the other sometimes gives negative values. 
VESC tools show accurate readings for both VESCs and both motors.
I also thought that the issue was about the Arduino Mega Ground port but the multimeter seems to output correct voltage when connected to it. However, When connecting or disconnecting the ground from the VESC to arduino the output values remain exactly the same which is why I believe the problem might come from the arduino side. Whatsmore, with the code that you made available, I cannot get data if I only link the TX1 (vesc) to RX1 (arduino) and the ground, I always need to connect RX and TX. Have tried for TX, RX 2 and 3 connections but I also get the same results.
I will do it with an Arduino Uno, but still trying to make the connection with the Software Serial.
Below are two pictures taken from two different VESCs. If you see any potential issue here let me know.
José

![rpm wrong reading](https://user-images.githubusercontent.com/37153384/58793895-faec1f80-85ee-11e9-8923-2953e8c3b72b.png)
![rpm wrong reading3](https://user-images.githubusercontent.com/37153384/58793903-ff183d00-85ee-11e9-854b-21d908c3acd4.png)

**Comment by Peemouse** [comment]
Please update to FW3.57. It fixes an issue about rpm data (not sure that it may be useful for you, but at least you're up to date).

Could you have a try with the example sketch "getValues" ?
I need to check the debug monitor on my side.

For connections, it's declared at the lines `UART.setSerialPort` for VESC and `UART.setDebugPort` for your computer.
Keep `Serial` for `UART.setDebugPort` and use either `Serial1`, `Serial2` or `Serial3` for `UART.setDebugPort` and connect your VESC according what you declared there.

**Comment by joseguerr** [comment]
The VESC tool only updates the firmware up to 3.56 on windows.. Regarding your last two paragraphs, every thing checks out. For the 3.56 version, the getValues sketch still gives me completly wrong values.

**Comment by Peemouse** [comment]
You need to download VESC Tool again for the latest version.

**Comment by joseguerr** [comment]
Thank you @Peemouse. One of the VESCs did not updated to 3.57 but i managed to update the second one (maybe i just bricked that one idk). However i still need to solder the pins on that VESC. Tomorrow i'll say how it went with the arduino.

**Comment by Peemouse** [comment]
Your non-udpating-FW VESC probably misses the bootloader.
Try again to upload the FW. If it still doen't take it, go in `Firmware -> Bootloader` tab and burn the bootloader.
Then try to update the FW again.

**Comment by joseguerr** [comment]
When I make the connection it does appear a message saying that it has the bootloader. However, when updating as usual it is not able to do it. I also tried to update through the bootloader, but without success. This is the message that appears when trying with the bootloader.
![bootloader](https://user-images.githubusercontent.com/37153384/58867388-41ef1900-86b2-11e9-8af9-b9b810a56790.png)

I am making the soldering on the second VESC to try the arduino code there. I'll keep you updated.

**Comment by Peemouse** [comment]
This is only a warning message. Nothing to do with the state of your VESC.
You need a ST-Link to recover your VESC.
Regarding this issue, I'll try to find time to power the bench and do some testing.
I'll report back.

**Comment by joseguerr** [comment]
Thank you @Peemouse , I'll get one of those.

**Comment by joseguerr** [comment]
Just tested the VESC tool 1.13 with FW 3.57 and still gave wrong values  rpm (other values were zero). If you manage to discover anything let me know. This was done using the getVescValues sketch.

![wrong reading FW 5 57](https://user-images.githubusercontent.com/37153384/58875027-589d6c00-86c2-11e9-8c78-3417debd9d91.PNG)

**Comment by joseguerr** [comment]
The arduino serial ports 1 and 2 are not functioning properly.. However RX and TX 3 worked for both your code and RollingGeeko's. Everything pointed towards an issue from the Arduino side and indeed it was. Sorry to bother you once more @Peemouse , have a great day!

**Comment by Peemouse** [comment]
Glad you found the issue.
Have a nice day.
