### ISSUE TITLE
How to use COMM_FORWARD_CAN to send commands to slave VESC

### ISSUE THREAD

**Issue by joseguerr** [Peemouse/VescUart#3]
Hi there @Peemouse 

Have been searching for some code that has this function implemented so I can use it in the arduino, but so far without success. I don't know what are the transformations required in the messages to actually send such command, using the libraries that are currently created.

The idea here was to sent commands to a slave vesc, for instance, setting RPM's. I've tested the CAN master-slave communication through VESC tool and is working well. It is just the code adaptation in c++ that I have no idea how to perform. I don't even know how is supposed to work with such function, while sending a command.

I would appreciate the help of anyone who reads this. Have a nice day!

**Comment by Peemouse** [comment]
Hi,
Have a look in my library. I implemented CAN Fwd in it for reteieving the PPM signal of the Master from the slave VESC.
You just need to wrap the command in the COMM_CAN_FORWARD one.
It's pretty easy.

**Comment by joseguerr** [comment]
What i need is to sent an rpm command to the VESC and the code tells how to retrieve the data from a master.. How would you change the code to sent RPM's commands? And what do you mean by "wrap the command"?

I thought you would need to change the code in c++ to actually send a message that includes the COMM_CAN_FORWARD but maybe is more simple than that. 

Sorry to bother you again, if you have time to put here a few lines of code or what does "wrap" translates into you would really appreciate. Cheers!

**Comment by joseguerr** [comment]
I found the code, will be playing with it. Once I manage to do it, i'll post something here.

**Comment by joseguerr** [comment]
Ok, I used this piece of code to try to run it, both with (payload,5) and (payload,7). Did not work.. 
The slave VESC lights up, so i don't know if I'm sending a wrong message. If you see any errors let me know.


void VescUart::setRPM(float rpm) {

		int32_t index = 0;
		uint8_t payload[5];

		payload[index++] = COMM_FORWARD_CAN;       
		payload[index++] = 1;                       
		payload[index++] = COMM_SET_RPM;
		buffer_append_int32(payload, (int32_t)(rpm), &index);

		packSendPayload(payload, 5);
	
}

**Comment by joseguerr** [comment]
It's done, the payload is changed to 7 and I cannot start the script with eRPM's =0. Basically I need to set the value to something that it will actually makes it spinning. Thanks again!

**Comment by Peemouse** [comment]
Glad you could find a workaround !
Feel free to submit a PR to integrate your function into my library.
